IA/Models/Comments.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IA.Models
{
    public class Comments
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("project")]
        public int project_Id { get; set; }
        public virtual projects project { get; set; }
        public string comment { get; set; }
    }
}

IA/Models/Schedule.cs
namespace IA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Schedule")]
    public partial class schedule
    {
        [Key]
        public int Id { get; set; }
        
        public string Start { get; set; }

        public string End { get; set; }

        public int Progress { get; set; }
        [ForeignKey("Project")]
        public int pId { get; set; }
        public virtual projects Project { get; set; }
        [ForeignKey("Team")]
        public int teamId { get; set; }
        public virtual team Team { get; set; }
    }
}

IA/Models/Team.cs
namespace IA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Team")]
    public partial class team
    {
        [Key]
        public int Id { get; set; }
        
        [ForeignKey("user")]
        public int? pmId{ get; set; }
        public virtual users user { get; set; }

        public virtual ICollection<schedule> Schedules { get; set; }
        
        public virtual ICollection<teamMember> Team_member { get; set; }

        public virtual ICollection<projects> Projects { get; set; }
        public virtual ICollection<Req_Team> tId { get; set; }
    }
}

IA/Models/report.cs
namespace IA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Report")]
    public partial class report
    {
        [Key]
        public int Id { get; set; }
        
        public string rdesc { get; set; }
        [ForeignKey("user")]
        public int? rUser { get; set; }
        public virtual users user { get; set; }
    }
}

IA/Controllers/ProjectManagerController.cs
using IA.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace IA.Controllers
{
    public class ProjectManagerController : Controller
    {
        // GET: ProjectManager
        private RealEstateContext db = new RealEstateContext();
        public ActionResult comment()
        {
            //ViewBag.Id = new SelectList(db.project, "Id", "pName");
            ViewBag.Id = db.project.Where(x=> x.Id > 0).ToList();
            Comments com = new Comments();
            return PartialView("_comment", com);
        }
        public ActionResult AddComment(Comments com,string pid)
        {
            int id = int.Parse(pid);
            com.project_Id = id;
            db.Comments.Add(com);
            db.SaveChanges();
            return RedirectToAction("Index","Profile");
        }
        //ended
        public ActionResult Exp_chart()
        {
            int ID = Convert.ToInt32(Session["ID"]);
            ViewBag.Exp = db.Experience.Where(x => x.userId == ID).ToList();
            return PartialView("chart");
        }
        public ActionResult cur_projects()
        {
            int ID = Convert.ToInt32(Session["ID"]);
            ViewBag.proj = db.project.Where(x => x.pmId == ID && x.progress == 1).ToList();
            return PartialView("curProj");
        }
        public ActionResult pre_project()
        {
            int ID = Convert.ToInt32(Session["ID"]);
            ViewBag.c_proj = db.project.Where(x => x.pmId == ID && x.progress == 2).ToList();
            return PartialView("prevProj");
        }
        public ActionResult cur_projects_list()
        {
            int ID = Convert.ToInt32(Session["ID"]);
            var project = db.project.Where(p => p.pmId == ID).Include(p => p.Customer).Include(p => p.Pm).Include(p => p.Team);
            ///////////////////////////////////////////////////////////////////
            List<schedule> sch = new List<schedule>();
            foreach (var item in project.ToList())
            {
                var s = db.schedule.Where(x => x.pId == item.Id).FirstOrDefault();
                if (s == null)
                {
                    s = new schedule();
                    s.Start = "0";
                    s.End = "0";
                }
                sch.Add(s);
            }
            ViewBag.sc = sch;
            ///////////////////////////////////////////////////////////////////
            return PartialView("_Control_project", project.ToList());
        }
        public ActionResult Edit(int id)
        {
            projects projects = db.project.Find(id);
            if (projects == null) { return HttpNotFound(); }
            ViewBag.customerId = new SelectList(db.users, "Id", "firstName", projects.customerId);
            ViewBag.pmId = new SelectList(db.users, "Id", "firstName", projects.pmId);
            ViewBag.pTeam = new SelectList(db.team, "Id", "Id", projects.pTeam);
            ///////////////////////////////////////////////////////////
            ViewBag.sch = db.schedule.Where(x=> x.pId == id && x.Progress == 1).ToList();
            ///////////////////////////////////////////////////////////
            return PartialView("_EditProj", projects);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,pName,pSalary,pDescription,pArea,pmId,customerId,pStatus,pTeam")] projects projects, string statue,string start,string end,string pId)
        {
            if (ModelState.IsValid)
            {
                /////////////////////////////////////////////////
                int pid = int.Parse(pId);
                var sc = db.schedule.Single(x=> x.pId == pid);
                sc.Start = start;
                sc.End = end;
                db.SaveChanges();
                /////////////////////////////////////////////////
                projects.progress = int.Parse(statue);
                db.Entry(projects).State = EntityState.Modified;
                projects.pmId = Convert.ToInt32(Session["ID"]);
                db.SaveChanges();
                Session["Valid_edit"] = 0;
                return RedirectToAction("Index", "Profile");
            }
            ViewBag.customerId = new SelectList(db.users, "Id", "firstName", projects.customerId);
            ViewBag.pmId = new SelectList(db.users, "Id", "firstName", projects.pmId);
            ViewBag.pTeam = new SelectList(db.team, "Id", "Id", projects.pTeam);
            Session["Valid_edit"] = 1;
            return RedirectToAction("Index", "Profile");
        }
        public ActionResult cancel(int? id)
        {
            //if (id == null){ return HttpNotFound(); }
            projects project = db.project.Find(id);
            //if (project == null){return HttpNotFound();}
            project.pmId = null;
            project.pStatus = 1;
            Session["Valid_edit"] = 0;
            db.SaveChanges();
            int ID = Convert.ToInt32(Session["ID"]);
            var projects = db.project.Where(p => p.pmId == ID).Include(p => p.Customer).Include(p => p.Pm).Include(p => p.Team);
            return PartialView("_Control_project", projects.ToList());
        }
        public ActionResult RequestView()
        {
            int ID = Convert.ToInt32(Session["ID"]);
            var req = db.Req_proj.Where(x => x.rPM == ID && x.rStatue == 0).ToList();
            return PartialView("Requests",req);
        }
        public ActionResult Accept(int id)
        {
            int ID = Convert.ToInt32(Session["ID"]);
            var req = db.Req_proj.Where(x => x.Id.Equals(id)).FirstOrDefault();
            var pro = db.project.Where(x => x.Id.Equals(req.rProject)).FirstOrDefault();
            req.rStatue = 1;
            pro.pStatus = 2;
            pro.pmId = ID;
            pro.progress = 1;
            db.SaveChanges();
            return RedirectToAction("Index", "Profile");
        }
        public ActionResult Reject(int id)
        {
            var req = db.Req_proj.Where(x => x.Id.Equals(id)).FirstOrDefault();
            req.rStatue = 2;
            db.SaveChanges();
            return RedirectToAction("Index", "Profile");
        }
        public ActionResult TeamView()
        {
            int ID = Convert.ToInt32(Session["ID"]);
            TeamView tv = new TeamView();
            tv.ourteam = db.team.Where(x=> x.pmId == ID).ToList();
            tv.users.AddRange(db.users.Where(x => x.userTypeId == 4).ToList());
            tv.users.AddRange(db.users.Where(x => x.userTypeId == 5).ToList());
            foreach (var item in tv.ourteam)
            {
                tv.tm.AddRange(db.teamMember.Where(x=>x.teamId == item.Id).ToList());
            }
            return PartialView("_TeamView",tv);
        }
        public ActionResult DeleteMember(int id)
        {
            var mem = db.teamMember.Where(x=>x.Id == id).FirstOrDefault();
            if (mem != null)
            {
                db.teamMember.Remove(mem);
                db.SaveChanges();
                return RedirectToAction("Index","Profile");
            }
            else
            {
                return HttpNotFound("Member Not found!");
            }
        }
        public ActionResult AddTeam()
        {
            int ID = Convert.ToInt32(Session["ID"]);
            team t = new team();
            t.pmId = ID;
            db.team.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index", "Profile");
        }
        public ActionResult DeleteTeam(string teamid)
        {
            try
            {
                int tmid = int.Parse(teamid);
                var team = db.team.Single(x => x.Id == tmid);
                if (team != null)
                {
                    db.team.Remove(team);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Profile");
                }
                else
                {
                    return HttpNotFound("Team Not found!");
                }
            }
            catch (Exception)
            {

                return RedirectToAction("Index", "Profile");
            }
        }
        public ActionResult TeamRequest(string userid,string teamid)
        {
            int ID = Convert.ToInt32(Session["ID"]);
            int uid = int.Parse(userid);
            int tmid = int.Parse(teamid);
            Req_Team rt = new Req_Team();
            rt.rPM = ID;
            rt.rTL = uid;
            rt.tId = tmid;
            rt.proId = null;
            rt.rStatue = 0;
            db.Req_Team.Add(rt);
            db.SaveChanges();
            return RedirectToAction("Index", "Profile");
        }
        public ActionResult ReportView()
        {
            var users = db.users.Where(x=> x.userTypeId == 2).ToList();
            return PartialView("ReportView",users);
        }
        public ActionResult Report(string custid,string report)
        {
            int cid = int.Parse(custid);
            report rp = new report();
            rp.rUser = cid;
            rp.rdesc = report;
            db.report.Add(rp);
            db.SaveChanges();
            return RedirectToAction("Index", "Profile");
        }
        public ActionResult ScheduleView()
        {
            int ID = Convert.ToInt32(Session["ID"]);
            var projects = db.project.Where(x => x.pmId == ID && x.pStatus == 2).ToList();
            ViewBag.teams = db.team.Where(x => x.pmId == ID).ToList();
            return PartialView("ScheduleView", projects);
        }
        public ActionResult Schedule(string proid,string teamid,string start,string end)
        {
            int pid = int.Parse(proid);
            int tid = int.Parse(teamid);
            schedule sch = new schedule();
            sch.pId = pid;
            sch.teamId = tid;
            sch.Start = start;
            sch.End = end;

IA/Views/ProjectManager/ReportView.cshtml
@model List<IA.Models.users>

<div class="col-sm-12">
    <h4 style="text-align:center;margin-bottom:30px">Send Report To Customer</h4>
    @using (Html.BeginForm("Report", "ProjectManager", FormMethod.Post, new { role = "form" }))
            {
        <div class="row">
            <div class="col-sm-4">
                <select class="form-control" name="custid" required style="margin-bottom:10px">
                    <option value="" selected disabled>choose Customer</option>
                    @foreach (var item in Model)
                    {
                        <option value="@item.Id">@item.firstName @item.lastName</option>
                    }
                </select>
            </div>
            <div class="col-sm-4 form-group">
                <input type="text" class="form-control" name="report" id="formGroupExampleInput" placeholder="Report">
            </div>
            <div class="col-sm-4">
                <input type="submit" id="submit" value="Send Request" style="margin:auto">
            </div>
        </div>
    }
</div>

IA/Views/ProjectManager/Requests.cshtml
@model List<IA.Models.Req_proj>

<div class="row">
    @*current and history columns*@
<div class="col-sm-12" style="height:300px;overflow:auto">
    <h4 style="text-align:center;font-weight:bold;border-bottom:solid 3px black;">Current Requests</h4>
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="row" style="margin-bottom:10px">
            <div class="col-sm-3" style="margin:auto">
                <label>Project: </label>
            </div>
            <div class="col-sm-3" style="margin:auto">
                <label>
                    @Html.DisplayFor(model => model[i].Project.pName)
                </label>
            </div>
            <div class="col-sm-3" style="text-align:center">
                <button class="btn btn-success">@Html.ActionLink("Accept", "Accept", "ProjectManager", new { id = Model[i].Id }, null)</button>
            </div>
            <div class="col-sm-3" style="text-align:center">
                <button class="btn btn-danger">@Html.ActionLink("Reject", "Reject", "ProjectManager", new { id = Model[i].Id }, null)</button>
            </div>
        </div>
    }
</div>
</div>

IA/Views/ProjectManager/ScheduleView.cshtml
@model List<IA.Models.projects>

<div class="col-sm-12">
    <h4 style="text-align:center;margin-bottom:30px">Send Report To Customer</h4>
    @using (Html.BeginForm("Schedule", "ProjectManager", FormMethod.Post, new { role = "form" }))
            {
                <div class="row">
                    <div class="col-sm-12">
                        <select class="form-control" name="proid" required style="margin-bottom:10px">
                            <option value="" selected disabled>choose Project</option>
                            @foreach (var item in Model)
                            {
                                <option value="@item.Id">@item.pName</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <select class="form-control" name="teamid" required style="margin-bottom:10px">
                            <option value="" selected disabled>choose Team</option>
                            @foreach (var item in ViewBag.teams)
                            {
                                <option value="@item.Id">Team @item.Id</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 form-group">
                        <input type="text" class="form-control" name="start" id="formGroupExampleInput" placeholder="Start Date">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 form-group">
                        <input type="text" class="form-control" name="end" id="formGroupExampleInput" placeholder="End Date">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-4">
                        <input type="submit" id="submit" value="Add Schedule" style="margin:auto">
                    </div>
                    <div class="col-sm-4"></div>
                </div>
            @*<div class="row">
                    <div class="col-sm-4">
                        <select class="form-control" name="proid" required style="margin-bottom:10px">
                            <option value="" selected disabled>choose Project</option>
                            @foreach (var item in Model)
                            {
                                <option value="@item.Id">@item.pName</option>
                            }
                        </select>
                    </div>
                    <div class="col-sm-4">
                        <select class="form-control" name="teamid" required style="margin-bottom:10px">
                            <option value="" selected disabled>choose Team</option>
                            @foreach (var item in ViewBag.teams)
                            {
                                <option value="@item.Id">Team @item.Id</option>
                            }
                        </select>
                    </div>
                    <div class="col-sm-4 form-group">
                        <input type="text" class="form-control" name="start" id="formGroupExampleInput" placeholder="Start Date">
                    </div>
                    <div class="col-sm-4 form-group">
                        <input type="text" class="form-control" name="end" id="formGroupExampleInput" placeholder="End Date">
                    </div>
                    <div class="col-sm-4">
                        <input type="submit" id="submit" value="Send Request" style="margin:auto">
                    </div>
                </div>*@
            }
        </div>

IA/Views/ProjectManager/_Control_project.cshtml
@model IEnumerable<IA.Models.projects>

<table class="table">
    <tr>
        <th>Customer Name</th>
        <th>Team's Id</th>
        <th>Project Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Area</th>
        <th>Progress</th>
        <th>Start</th>
        <th>End</th>
    </tr>
    @{ int i = 0;}
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.firstName) @Html.DisplayFor(modelItem => item.Customer.lastName)
            </td>
            <td>@Html.DisplayFor(modelItem => item.Team.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.pName)</td>
            <td>@Html.DisplayFor(modelItem => item.pSalary)</td>
            <td>@Html.DisplayFor(modelItem => item.pDescription)</td>
            <td>@Html.DisplayFor(modelItem => item.pArea)</td>
            <td>
                @if (Convert.ToInt32(item.progress) == 1)
                {<label>In Progress</label>}
                else {<label>Delivried</label>}
            </td>
            <td>@ViewBag.sc[i].Start</td>
            <td>@ViewBag.sc[i].End</td>
            @{i = i + 1;}
            <td>
                @{ int ID = Convert.ToInt32(item.Id);}
                <input type="button" class="btn btn-primary btn-sm" style="margin-bottom:2px;" id="edit" onclick="pass(@ID)" value="Edit" />
                <input type="button" class="btn btn-primary btn-sm" style="margin-top:2px;" id="del" onclick="cancel(@ID)" value="Cancel" />
            </td>
        </tr>
     }
</table>

<script type="text/javascript">
    function pass(variable) {
        $('#state').empty();
        var url = '@Url.Action("Edit", "ProjectManager")';
        $.ajax({
            url: url,
            type: 'GET',
            cache: false,
            data: { id: variable },
            success: function (result) {
                $('#state').html(result);
            }
        });
    }
    function cancel(variable) {
        $('#state').empty();
        var url = '@Url.Action("cancel", "ProjectManager")';
        $.ajax({
            url: url,
            type: 'GET',
            cache: false,
            data: { id: variable },
            success: function (result) {
                $('#state').html(result);
            }
        });
    }
    function comment(variable) {
    $('#state').empty();
    var url = '@Url.Action("comment", "ProjectManager")';
    $.ajax({
        url: url,
        type: 'GET',
        cache: false,
        data: { id: variable },
        success: function (result) {
            $('#state').html(result);
        }
    });
    }
</script>

IA/Views/ProjectManager/_TeamView.cshtml
@model IA.Models.TeamView


<div>
    <h3 style="text-align: center;">Members</h3>
    <hr/>
    <div class="row" style="width:100%;font-size:20px;">
        <div class="col-lg-4">Team Number</div>
        <div class="col-lg-5">Member Name</div>
    </div>
    <hr/>
    @foreach (var item in Model.tm)
    {
        <div class="row" style="width:100%">
            <div class="col-lg-4">@item.teamId</div>
            <div class="col-lg-4">@item.user.firstName</div>
            <div class="col-lg-4">@Html.ActionLink("Delete", "DeleteMember", "ProjectManager", new { id = item.Id }, null)</div>
        </div>
        <hr />
    }
</div>

<div>
    <h3 style="text-align: center;margin-bottom:20px">Add and Delete Teams</h3>
    <div class="row" style="width:100%">
        <div class="col-sm-12">
            @using (Html.BeginForm("DeleteTeam", "ProjectManager", FormMethod.Post, new { role = "form" }))
            {
                <div class="row">
                    <div class="col-sm-6" style="margin:auto">
                        <select class="form-control" name="teamid" required style="margin-bottom:10px">
                            <option value="" selected disabled>choose Team</option>
                            @foreach (var item in Model.ourteam)
                            {
                                <option value="@item.Id">Team @item.Id</option>
                            }
                        </select>
                    </div>
                    <div class="col-sm-3">
                        <input type="submit" id="submit" value="Delete" style="margin:auto">
                    </div>
                    <div class="col-sm-3" style="margin:auto;text-align:center">@Html.ActionLink("Add Team", "AddTeam", "ProjectManager", null, null)</div>
                </div>
            }
        </div>
    </div>
    <hr />
</div>

<div>
    <h3 style="text-align: center;margin-bottom:20px">Send Request</h3>
    <div class="row" style="width:100%">
        <div class="col-sm-12">
            @using (Html.BeginForm("TeamRequest", "ProjectManager", FormMethod.Post, new { role = "form" }))
            {
                <div class="row">
                    <div class="col-sm-4" style="margin:auto">
                        <select class="form-control" name="userid" required style="margin-bottom:10px">
                            <option value="" selected disabled>choose Member</option>
                            @foreach (var item in Model.users)
                            {
                                <option value="@item.Id">@item.firstName @item.lastName</option>
                            }
                        </select>
                    </div>
                    <div class="col-sm-4" style="margin:auto">
                        <select class="form-control" name="teamid" required style="margin-bottom:10px">
                            <option value="" selected disabled>choose Team</option>
                            @foreach (var item in Model.ourteam)
                            {
                                <option value="@item.Id">Team @item.Id</option>
                            }
                        </select>
                        
                    </div>
                    <div class="col-sm-4">
                        <input type="submit" id="submit" value="Send Request" style="margin:auto">
                    </div>
                </div>
            }
        </div>
    </div>
    <hr />
</div>

IA/Views/ProjectManager/_comment.cshtml
@model IA.Models.Comments
@using (Html.BeginForm("AddComment", "ProjectManager", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Comments</h4>
        <hr />
        <div class="form-group">
            <h4> Project Name </h4>
            <div class="col-md-8">
                <select class="form-control" name="pid" required style="margin-bottom:10px">
                    <option value="" selected disabled>choose project</option>
                    @foreach (var item in ViewBag.Id)
                    {
                        <option value="@item.Id">@item.pName</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.comment, 10, 60, new { @class = "form-control required", style = "max-width:75% !important;" })
            </div>
        </div>

        <!--Textarea with icon prefix-->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

IA/Views/ProjectManager/chart.cshtml
<div id="piechart" style="width: 900px; height: 500px;" class="property horizontal d-flex"></div>
<script>
google.charts.load('current', { 'packages': ['corechart'] });
google.charts.setOnLoadCallback(drawChart);
function drawChart()
{
    var Namearray = [];
    var years = [];
        @foreach (var item in ViewBag.Exp)
        {
            @:Namearray.push("@item.E_Name");
            @:years.push("@item.year");
        }
    var data = new google.visualization.DataTable();
    var options = {is3D: true,};
    data.addColumn('string', 'Experience');
    data.addColumn('number', 'number of years');
    var year;
    for (i = 0; i < Namearray.length; i++) {
        year = parseInt(years[i], 10)
        data.addRow([Namearray[i].toString(), year]);
    }
    var chart = new google.visualization.PieChart(document.getElementById('piechart'));
    chart.draw(data, options);
}
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

IA/Views/ProjectManager/curProj.cshtml
<div id="proj">
    <div>
        <div class="row">
            <div class="col-sm-12">
                @foreach (var item in ViewBag.proj)
                {
                    <strong class="price"> @item.pName  </strong>
                    <ul class="w border-r">
                        <li> Salary : @item.pSalary </li>
                        <li> Description : @item.pDescription </li>
                        <li> Area : @item.pArea </li>
                    </ul>
                }
            </div>
        </div>
    </div>
</div>

IA/Views/ProjectManager/editProject.cshtml
@model IA.Models.projects
<div class="row">
    <div class="col-md-12 mb-5">
        @using (Html.BeginForm("update", "ProjectManager"))
        {
            <h2 class="h4 text-black mb-5">@Html.DisplayFor(model=>model.pName)</h2>
                
                <div class="row form-group">
                    <div class="col-md-12">
                        <label class="text-black" for="message">Salary</label>
                        @Html.TextBoxFor(p => p.pSalary, new { @class = "form-control", @placeholder = "Enter Project Area", @required = "required", @type = "number" })
                        @Html.ValidationMessageFor(p => p.pSalary)
                    </div>
                </div>
                <div class="form-group">
                    <h4> Progress </h4>
                    <div class="col-md-10">
                        <select name="statue" id="q_rate" class="form-control">
                            <option value="2">In-Progress</option>
                            <option value="3">Deliveried</option>
                        </select>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-12">
                        @Html.HiddenFor(p => p.Id)
                        <button type="submit" class="btn btn-primary btn-md text-white"> Save </button>
                    </div>
                </div>

        }
    </div>
</div>

IA/Views/ProjectManager/prevProj.cshtml
<div id="proj2">
    <div>
        <div class="row">
            <div class="col-sm-12">
                @foreach (var item in ViewBag.c_proj)
                {
                    <strong class="price"> @item.pName </strong>
                    <ul class="w border-r">
                        <li> Salary : @item.pSalary </li>
                        <li> Description : @item.pDescription</li>
                        <li> Area : @item.pArea </li>
                    </ul>
                }
            </div>
        </div>
    </div>
</div>